### ISSUE TITLE
オプションを必須パラメータにしない

### ISSUE THREAD

**Issue by naitwo2** [ap-communications/NEEDLEWORK-ScenarioWriter#3]
`disable_policy_output`オプションが必須パラメータになっているので、以下の対応（どちらか）をしていただけると助かります。

* 指定されていない場合はエラーメッセージを出す（現状は出力されない）
* 必須パラメータから除外する

**Comment by kotakahashi** [comment]
commit hash : `7e603f657966a47152658abf20dca13cf46e8766`で対応したためクローズ
